name: CI

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run l:c

      - name: Check formatting (Prettier)
        run: npm run p:c

      - name: Run Unit Tests
        run: npm run test

      - name: Create build for Playwright tests and typechecking
        run: npm run build:test

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1
