name: CI

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run l:c

      - name: Check formatting (Prettier)
        run: npm run p:c

      - name: Build TypeScript
        run: npm run build

      - name: Run Tests
        run: npm run test
