name: CI Prod

on:
  pull_request:
    branches:
      - main

jobs:
  code_checks:
    name: Code Checks
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run l:c

      - name: Check formatting (Prettier)
        run: npm run p:c

      - name: Run Unit Tests
        run: npm run test
